### ISSUE TITLE
Cannot make new session with session key

### ISSUE THREAD

**Issue by ghost** [sosedoff/grooveshark#33]
I followed the simple instructions in the README but could not have success using a session key. 
I performed the command to get stream links for a song but could not actually play the song in my browser. Any idea how to fix this?

The trace from the session key attempt is below:

2.1.2 :001 > require 'grooveshark'

 => true 

2.1.2 :002 > client = Grooveshark::Client.new

 => #<Grooveshark::Client:0x00000003ec46d8 @ttl=120, @uuid="B2F32520-0CAE-0132-2407-201A068DBB95", @comm_token="73cd9646c66d2c807862b26791e5897c572ba7b0", @comm_token_ttl=1408769330, @country={"ID"=>223, "CC1"=>0, "CC2"=>0, "CC3"=>0, "CC4"=>1073741824, "DMA"=>807, "iso"=>"US", "region"=>"CA", "city"=>"San Francisco", "zip"=

2.1.2 :002 > client = Grooveshark::Client.new

 => #<Grooveshark::Client:0x00000003ec46d8 @ttl=120, @uuid="B2F32520-0CAE-0132-2407-201A068DBB95", @comm_token="73cd9646c66d2c807862b26791e5897c572ba7b0", @comm_token_ttl=1408769330, @country={"ID"=>223, "CC1"=>0, "CC2"=>0, "CC3"=>0, "CC4"=>1073741824, "DMA"=>807, "iso"=>"US", "region"=>"CA", "city"=>"San Francisco", "zip"=>"94110", "IPR"=>0}, @session="3d17c63f4ec8f7028753c4ea0c9dcfd2"> 

2.1.2 :003 > session = client.session

 => "3d17c63f4ec8f7028753c4ea0c9dcfd2" 

2.1.2 :004 > client = Grooveshark::Client.new(session)

TypeError: no implicit conversion of Symbol into Integer
    from /home/max/.rvm/gems/ruby-2.1.2/gems/grooveshark-0.2.11/lib/grooveshark/client.rb:7:in `[]'
    from /home/max/.rvm/gems/ruby-2.1.2/gems/grooveshark-0.2.11/lib/grooveshark/client.rb:7:in`initialize'
    from (irb):4:in `new'
    from (irb):4
    from /home/max/.rvm/rubies/ruby-2.1.2/bin/irb:11:in`<main>'

**Comment by MaxPleaner** [comment]
i'm actually just now realizing that i should check the github notifications page. thanks for responding. I tried 2.0 but had the same problem. Looking into the client.rb file, though, it's pretty clear where the problem was
```ruby
    def initialize(params = {})                                                                                                             
      @ttl = params[:ttl]
```
since the readme says that Session Keys can be reused with
`Grooveshark::Client.new(SESSION_KEY)`, params was a string and threw the error in response to the [:ttl] call.

Anyway, thanks for making this!

**Comment by PierreRambaud** [comment]
Hi,

Yes, since 2012 (v0.2.5), grooveshark doesn't only need session to works. A valid token must be used when building requests, so it's better to use login method instead.
I fix the README, thanks for the catch.

Regards,
