### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by PierreRambaud** [sosedoff/grooveshark#44]
Hi,
Can you release a new version for integrating latest bugs fixes.
Regards

**Comment by sosedoff** [comment]
Done. v0.2.13 is released

**Comment by PierreRambaud** [comment]
Thanks a lot

**Comment by sosedoff** [comment]
@PierreRambaud i added you as collaborator.

**Comment by PierreRambaud** [comment]
Thanks, I was planning to get back to my software ;)

**Comment by PierreRambaud** [comment]
Is it possible to have the permission to push gem on rubygems.org? (https://rubygems.org/profiles/PierreRambaud)

Regards

**Comment by sosedoff** [comment]
Sure, i can add you.

**Comment by sosedoff** [comment]
Pushed latest 0.2.14, also would need your email to add to owners.

**Comment by PierreRambaud** [comment]
here's my email used for rubygems: pierre.rambaud86@gmail.com

**Comment by sosedoff** [comment]
Added, you can now push to rubygems. Use `rake release` command.
