### ISSUE TITLE
Help (Ubuntu)

### ISSUE THREAD

**Issue by Mbeardmore** [sosedoff/grooveshark#45]
so basically ive installed all the files needed now i just basically require help using the files if you could help id be most appreciative im down to the usage part but have no idea how to find the things it says

**Comment by PierreRambaud** [comment]
Hi,

Can you tell me more about what you want to do exactly?
Don't forget it's just an API, you must know how to write Ruby code.
If you just want to search musics, playlist, or download them, you can have a look on https://github.com/PierreRambaud/groove-dl repository.

Regards
